// Senate LDA General Issue Codes → Human-Readable Names
// Source: lda.senate.gov API + lda.congress.gov/ld/help/Documents/AppCodes.htm

export const ISSUE_CODES: Record<string, string> = {
  ACC: 'Accounting',
  ADV: 'Advertising',
  AER: 'Aerospace',
  AGR: 'Agriculture',
  ALC: 'Alcohol & Drug Abuse',
  ANI: 'Animals',
  APP: 'Apparel/Clothing/Textiles',
  ART: 'Arts/Entertainment',
  AUT: 'Automotive Industry',
  AVI: 'Aviation/Airlines/Airports',
  BAN: 'Banking',
  BEV: 'Beverage Industry',
  BNK: 'Bankruptcy',
  BUD: 'Budget/Appropriations',
  CAW: 'Clean Air & Water',
  CDT: 'Commodities',
  CHM: 'Chemicals/Chemical Industry',
  CIV: 'Civil Rights/Civil Liberties',
  COM: 'Communications/Broadcasting/Radio/TV',
  CON: 'Constitution',
  CPI: 'Computer Industry',
  CPT: 'Copyright/Patent/Trademark',
  CSP: 'Consumer Issues/Safety/Products',
  DEF: 'Defense',
  DIS: 'Disaster Planning/Emergencies',
  DOC: 'District of Columbia',
  ECN: 'Economics/Economic Development',
  EDU: 'Education',
  ENG: 'Energy/Nuclear',
  ENV: 'Environment/Superfund',
  FAM: 'Family Issues/Abortion/Adoption',
  FIN: 'Financial Institutions/Investments/Securities',
  FIR: 'Firearms/Guns/Ammunition',
  FOO: 'Food Industry (Safety, Labeling)',
  FOR: 'Foreign Relations',
  FUE: 'Fuel/Gas/Oil',
  GAM: 'Gaming/Gambling/Casino',
  GOV: 'Government Issues',
  HCR: 'Health Issues',
  HOM: 'Homeland Security',
  HOU: 'Housing',
  IMM: 'Immigration',
  IND: 'Indian/Native American Affairs',
  INS: 'Insurance',
  INT: 'Intelligence',
  LAW: 'Law Enforcement/Crime/Criminal Justice',
  LBR: 'Labor Issues/Antitrust/Workplace',
  MAN: 'Manufacturing',
  MAR: 'Marine/Maritime/Boating/Fisheries',
  MED: 'Medical/Disease Research/Clinical Labs',
  MIA: 'Media (Information/Publishing)',
  MMM: 'Medicare/Medicaid',
  MON: 'Minting/Money/Gold Standard',
  NAT: 'Natural Resources',
  PHA: 'Pharmacy',
  POS: 'Postal',
  REL: 'Religion',
  RES: 'Real Estate/Land Use/Conservation',
  RET: 'Retirement',
  ROD: 'Roads/Highway',
  RRR: 'Railroads',
  SCI: 'Science/Technology',
  SMB: 'Small Business',
  SPO: 'Sports/Athletics',
  TAR: 'Tariff (Duties/Imports)',
  TAX: 'Taxation/Internal Revenue Code',
  TEC: 'Telecommunications',
  TOB: 'Tobacco',
  TOR: 'Torts',
  TOU: 'Tourism/Travel',
  TRA: 'Transportation',
  TRD: 'Trade (Domestic/Foreign)',
  TRU: 'Trucking/Shipping',
  UNM: 'Unemployment',
  URB: 'Urban Development/Municipalities',
  UTI: 'Utilities',
  VET: 'Veterans',
  WAS: 'Waste (Hazardous/Solid/Interstate/Nuclear)',
  WEL: 'Welfare',
}

export function getIssueName(code: string): string {
  return ISSUE_CODES[code] || code
}

// Group issue codes into broader sectors for analysis
export const ISSUE_SECTORS: Record<string, string[]> = {
  'Healthcare & Pharma': ['HCR', 'MED', 'PHA', 'MMM'],
  'Defense & Security': ['DEF', 'HOM', 'INT', 'AER', 'FIR'],
  'Energy & Environment': ['ENG', 'FUE', 'ENV', 'CAW', 'NAT', 'WAS', 'UTI'],
  'Finance & Business': ['BAN', 'FIN', 'INS', 'ACC', 'BNK', 'SMB', 'RET', 'TAX'],
  'Technology & Telecom': ['TEC', 'CPI', 'COM', 'CPT', 'SCI', 'MIA'],
  'Transportation': ['TRA', 'AVI', 'AUT', 'RRR', 'ROD', 'TRU', 'MAR'],
  'Agriculture & Food': ['AGR', 'FOO', 'BEV', 'TOB', 'ANI'],
  'Government & Law': ['GOV', 'BUD', 'LAW', 'CIV', 'CON', 'DOC', 'IMM', 'FOR'],
  'Social Issues': ['EDU', 'HOU', 'FAM', 'WEL', 'UNM', 'LBR', 'VET', 'REL', 'IND'],
  'Trade & Economy': ['TRD', 'TAR', 'ECN', 'MAN', 'CDT', 'MON'],
  'Other': ['ADV', 'ALC', 'APP', 'ART', 'CSP', 'DIS', 'GAM', 'POS', 'RES', 'SPO', 'TOR', 'TOU', 'URB'],
}
